### PR TITLE
Add compatibility notice for 6.2.60 release.

### PR DESCRIPTION
**Pull request by racke**
The idea is to highlight changes that affect an existing installation in an unexpected way and may require listmasters to adjust their configuration.

### CODE REVIEW

**Comment by ikedas** [comment]
Your idea sounds good, but what is the defference between "Compatibility notice" and "Changes" section?
-  I think the "Changes" section was added to note significant changes administrators have to take care.  
- Among them, compatibility concerns are gathered into the "Upgrading notes" (More strictly, automated updates like chages on database structure are omitted).  Administrators may read through this page instead of  jumping around each section in NEWS.md.

EDIT:

Ah..., the feature about "dump files" (`member.dump` etc.) that was added around 6.2.34 has not been noted in Upgrading notes.  This is the "big change" David blamed, isn't it?  I'll add it later...

**Comment by racke** [comment]
I want to make sure that the administrators see "Compatibility" changes in the top spot. If they don't notice it here, than it is really their fault. 

So we have the "merge" and "setuid" entries pointing to the "Upgrading notes". 

While "setuid" is important, it will *not* change the current behaviour. That's the difference.

Aside from that I suggest to prepare a document how these setuid settings work and how you run Sympa entirely as Sympa user.

**Comment by ikedas** [comment]
> I want to make sure that the administrators see "Compatibility" changes in the top spot. If they don't notice it here, than it is really their fault.
> 
> So we have the "merge" and "setuid" entries pointing to the "Upgrading notes".
> 
> While "setuid" is important, it will _not_ change the current behaviour. That's the difference.

Indeed I felt strange myself putting things about setuid in "Changes" section.  In the cases so far they would be put in "Implemented enhancements" section.

How about (moving setuid things and) changing "Changes" section to "Incompatible changes" from this time forward?

> 
> Aside from that I suggest to prepare a document how these setuid settings work and how you run Sympa entirely as Sympa user.

Sounds nice!

**Comment by racke** [comment]
Yes, we could group it into "Incompatible Changes", "Enhancements" and "Bug Fixes".

**Comment by ikedas** [comment]
Merged & force-pushed.

**Pull request closed without merging**
